# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Internal Testing

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, ready_for_review, opened, synchronize, reopened]
    branches:
      - main

jobs:
  test:
    name: Run all tests
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
      - run: npm ci
      - run: npm test
